### ISSUE TITLE
Support of /spi/ and /api/

### ISSUE THREAD

**Issue by zonito** [cloudendpoints/endpoints-python#116]
please add support for both prefixes:
`/_ah/spi/...` and `/_ah/api/...`

For spi, I am having issue with `/_ah/spi/BackendService.getApiConfigs` with v2 version.

**Comment by inklesspen** [comment]
`/_ah/spi/` is not supported and will not be supported. You should use `/_ah/api/` or specify [an alternate path as shown in the docs](https://cloud.google.com/endpoints/docs/frameworks/python/api_server).
