### ISSUE TITLE
messages.IntegerField converted into string

### ISSUE THREAD

**Issue by lcasartelli** [cloudendpoints/endpoints-python#129]
messages.IntegerField isn't handled properly in JSON responses.
If you try to define and use a message with an integer field (for example `amount`), the JSON response will be an object that contains a property with a string value instead of an integer value (in the example `{ "amount": "12345"}`), the integer value assigned is always converted into a string.

**Comment by tangiel** [comment]
Is your value expected to exceed the value of a 32-bit integer? If not, I think adding `variant=Variant.INT32` will fix it. The `Variant` class is in `protorpc.messages`.
