### ISSUE TITLE
Compatibility issues with google-api-python-client 1.0+

### ISSUE THREAD

**Issue by sandeepkoduri** [cloudendpoints/endpoints-python#16]
we have been using google-api-python-client 1.0+ for a while now.
I tried to upgrade to endpoint2.0, both libraries have dependency on oauth2client. 

Is this a know issues or is there any work around.

**Comment by sandeepkoduri** [comment]
Any update on update to supported libraries. We can't downgrade other libraries to use this package. is there any chance on ETA when this can be fixed?

**Comment by inklesspen** [comment]
Can you please explain the difficulty? I can't find a google-api-python-client 2.0+; all I can find is google-api-python-client [1.6.4](https://pypi.python.org/pypi/google-api-python-client/1.6.4).

google-api-python-client 1.6.4 requires `oauth2client>=1.5.0,<5.0.0dev`, while the Endpoints frameworks require  `oauth2client>=2.0.0,<4.0.0dev`. oauth2client 3.0.0 would seem to satisfy both requirements.

**Comment by inklesspen** [comment]
Did you see the fix on https://github.com/cloudendpoints/endpoints-management-python/issues/21 ? Does that fix the issue for you?

**Comment by sandeepkoduri** [comment]
I figured the issue, the library is not compatible with oauth2client 4.0.0, I figured it out after a day. 
I used the oauth2client 3.0.0 that worked. 

I was already using oauth2client 4.0.0, I installed endpoint 2.3 with pip, it installed smoothly and added apitools latest version which has:
from oauth2client import locked_file
ImportError: cannot import name locked_file

**Comment by inklesspen** [comment]
Yes, you have to be very careful about which versions you use. Unfortunately, some of these libraries are not actively in development, but we do not have the resources at this time to switch to newer libraries. If you stick to the versions specified by our requirements, you should be fine.
