### ISSUE TITLE
Cloud Endpoints, support Google App Engine Standard for Python 3.x

### ISSUE THREAD

**Issue by hashikami** [cloudendpoints/endpoints-python#194]
I have 2 questions.

1. When will Cloud Endpoints support Google App Engine (GAE) standard environment for python 3.x? 
As you know, in https://cloud.google.com/endpoints/docs/frameworks/python/get-started-frameworks-python, "Note: Make sure you have Python 2.7.x installed. python 3.x isn't supported by Endpoints Frameworks." Even though python 2.7.x is end of support this year, I can not upgrade to python 3 using Endpoints Frameworks in GAE standard environment. 
Unfortunately, I could not find out features in this repository.

2. If the Endpoints Frameworks is not supported for GAE standard for python 3, what library should I use?

Kind Regards,

**Comment by ndrd** [comment]
Why are you closing this issue? There are no intentions of provide a version for python 3?
Next year python 2.7 reaches EOL!
