### ISSUE TITLE
Discovery doc not generating on GAE

### ISSUE THREAD

**Issue by Synthoova** [cloudendpoints/endpoints-python#33]
I'm having an issue with my application that I've not been able to solve. Everything had been working fine, and as I have made very minimal changes since version 2.0.0b7 of endpoints-python was released, I'm posting this issue as I believe the source of the error may be originating inside endpoints-python.

For testing purposes, I make use of Google's API explorer tool to easily make calls against my api. This has been working fine. Now though, I'm getting an error in my logs that reads as follows:

> No discovery doc for version 1.0 of api...

This originates at discovery_service.py:115.

I get this error every time I try to use the API Explorer, which I assume queries the discovery service. However, upon further digging, I noticed that I don't get the same error when I'm on the [default] service; it only happens when I'm within a named service, as defined (or not) in my app.yaml files.

For example, if my app.yaml is as follows:

```
runtime: python27
threadsafe: true
api_version: 1

...skip files stuff....

handlers:
- url: /_ah/api/.*
  script: core.api
```

All is well. But if I include:

`service: telephony`

Then discovery generation fails.

Digging a little deeper I noticed that when I visit:

`https://telephony-dot-REDACTED.appspot.com/_ah/api/discovery/v1/apis`

The discovery JSON that I get is as follows:

```
{
 "kind": "discovery#directoryList",
 "discoveryVersion": "v1",
 "items": [
  {
   "kind": "discovery#directoryItem",
   "id": "telephony:v1.0",
   "name": "telephony",
   "version": "v1.0",
   "title": "Wrapped Telephony services",
   "description": "This is an API",
   "discoveryRestUrl": "https://REDACTED.appspot.com/_ah/api/discovery/v1/apis/telephony/v1.0/rest",
   "discoveryLink": "./apis/telephony/v1.0/rest",
   "icons": {
    "x16": "https://www.gstatic.com/images/branding/product/1x/googleg_16dp.png",
    "x32": "https://www.gstatic.com/images/branding/product/1x/googleg_32dp.png"
   },
   "preferred": true
  }
 ]
}
```

Note that the `discoveryRestUrl` above is incorrect. It should be:

`https://telephony.REDACTED.appspot.com/_ah/api/discovery/v1/apis/telephony/v1.0/rest`

-or-

`https://telephony-dot-REDACTED.appspot.com/_ah/api/discovery/v1/apis/telephony/v1.0/rest`

If I then browse to the correct URL, I get a valid REST discovery JSON file, which in my case, begins as follows:

```
{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        }
      }
    }
  },
  "basePath": "/_ah/api/telephony/v1.0/",
  "baseUrl": "https://REDACTED.appspot.com/_ah/api/telephony/v1.0/",
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "icons": {
    "x16": "http://www.google.com/images/icons/product/search-16.gif",
    "x32": "http://www.google.com/images/icons/product/search-32.gif"
  },
  "id": "telephony:v1.0",
  "kind": "discovery#restDescription",
  "name": "telephony",
  "parameters": {

...
```

Here I'm less sure, but I believe the `baseUrl` should also contain the service name, no?

I've reviewed the recent changes to discovery_service.py, but the recent introduction of discovery_generator.py (and therefore lack of change history to review) all but collapsed my desire to dig much further for an easy fix.

For completeness sake, I did test using the local development server, but didn't get the same behaviour because the development tool doesn't seem to serve differently if a service name is provided. So, the discovery docs seem to be right as they should be. Oddly though, locally, I can't get the API Explorer to actually load the api. Yes, I'm configuring Chrome correctly, per the documentation. The API Explorer loads up, but it won't show my api, even for the one that works fine on App Engine. Perhaps running endpoints locally still doesn't work?

I'm sorry if this is unclear. I'm happy to provide further details. My implementation is very basic, so my feeling is that this should work, as it had been. I've not made any changes to my app.yaml file recently (except updating the `ENDPOINTS_SERVICE_VERSION` as required). My api classes have also not changed since it was last working.

I'm on:

endpoints v2.0.0b7
endpoints_api_management v1.0.0b9
gcloud sdk v138.0.0 with updated components.

I'm using the App Engine SDK packaged within the Cloud SDK.

My endpoints classes use the api_collection decorator so I can have multiple classes.

Interested in whatever thoughts you may have. I'd really like this to be working again so I can continue testing.

**Comment by bradfriedman** [comment]
Thanks for bringing this up! Discovery doc generation used to be outsourced to another Google service, but we recently brought it into the Endpoints package for local, emulated generation, which is why discovery_generator.py is new and lacks revision history. Looks like there's an issue with that emulation. I'll look into it!

**Comment by Synthoova** [comment]
Excellent. I'll wait for a fix.

In the meantime, I'm testing by just swapping out my [default] service all the time, which seems unaffected by this problem.

**Comment by bradfriedman** [comment]
There's a PR for this currently in review! Should be merged soon.

**Comment by bradfriedman** [comment]
This has been merged! It will be part of the next release. :)
