### ISSUE TITLE
x-issuer and x-jwks_uri Extensions Are Deprecated

### ISSUE THREAD

**Issue by Synthoova** [cloudendpoints/endpoints-python#36]
The Google Cloud SDK is giving the following warning to openapi specifications generated by endpoints:

> WARNING: mysystemv1.0openapi.json: x-issuer: Extension name x-issuer has been deprecated, please rename it to x-google-issuer.
WARNING: mysystemv1.0openapi.json: x-jwks_uri: Extension name x-jwks_uri has been deprecated, please rename it to x-google-jwks_uri.

openapi_generator.py probably just needs a small edit to rename them.

**Comment by bradfriedman** [comment]
I have a PR in place to fix this for the next minor release :)

**Comment by bradfriedman** [comment]
This has been pushed and will be released soon!
