### ISSUE TITLE
Latest gcloud version breaks endpointscfg gen_client_lib

### ISSUE THREAD

**Issue by tekulvw** [cloudendpoints/endpoints-python#56]
The latest version of `gcloud` has deprecated the `application` key in `app.yaml` which is required for `gen_client_lib` to create a working library (for Java at least in my limited testing).

`gcloud version` output:

```Google Cloud SDK 148.0.0
app-engine-python 1.9.50
bq 2.0.24
bq-nix 2.0.24
core 2017.03.17
core-nix 2017.03.13
gcloud 
gcloud-deps 2017.03.17
gcloud-deps-linux-x86_64 2017.03.13
gsutil 4.23
gsutil-nix 4.22
```

**Comment by inklesspen** [comment]
This is no longer broken; I have successfully generated a Java client library.
