### ISSUE TITLE
get_openapi_spec will only generate schemes with "http"

### ISSUE THREAD

**Issue by mlcrazy** [cloudendpoints/endpoints-python#59]
I can't figure out how to generate a open api spec json file with the correct schemes that would include "https", when I generate my file locally with a command like this:

`$python lib/endpoints/endpointscfg.py get_openapi_spec main.CoreApi --hostname core-api-dot-dev-sada-gcs.appspot.com`

util.is_running_on_devserver() will always return this as being a "Development" server because locally I'm using google cloud SDK to generate the spec file.

Am I doing this wrong? Is there a better way to do this that will generate the spec file with an "https" in schemes?

https://github.com/cloudendpoints/endpoints-python/blob/e27f8b057c6e30148a87aec6d66f6f174a7c80a8/endpoints/util.py#L190-L191

**Comment by inklesspen** [comment]
Bug hidden from tests by #94
