### ISSUE TITLE
Deploy endpoints 2.0 in an app engine old version isn't updating api explorer

### ISSUE THREAD

**Issue by omarcoteixeira** [cloudendpoints/endpoints-python#66]
I'm trying to update an app version appengine called "development" and was **created with endpoints 1.0** with endpoints version **2.0**. 

When I update the "development" version with endpoints 2.0 and I go to Api Explorer, the Api Explorer still with the old version of the API (created with endpoints 1.0).
When I do the deploy in a new version called "development-endpoints2o" and I go to Api Explorer, it works correctly.

Has anyone ever had this problem?
I think it's kind of  cache problem or something. Is there any way to solve this?

I'm using python with endpoints 2.0.6.
Thanks.

**Comment by tangiel** [comment]
@omarcoteixeira it may be an issue with caching. If your development version is not critical, I suggest deleting and re-deploying the version.

**Comment by omarcoteixeira** [comment]
@tangiel I tried but it still continues there with old version if I create with the same name. I create a new one with a different name and works.
