### ISSUE TITLE
'Path used multiple times' when migrating to v2

### ISSUE THREAD

**Issue by ValentinCoudert** [cloudendpoints/endpoints-python#74]
(Also on [Stackoverflow](https://stackoverflow.com/questions/45480401/path-used-multiple-times-when-migrating-to-google-cloud-enpoints-v2))

Hello

I tried to follow [the steps to migrate to v2](https://cloud.google.com/endpoints/docs/frameworks/legacy/v1/python/migrating) (appengine app) and faced what seems to be a bug.

I have multiple APIs under the same AppEngine service (pretty much like [here](https://github.com/cloudendpoints/endpoints-python/issues/47)), and changed my `app.yaml`, downloaded the `cloud-endpoints` library, put it in the `/lib` folder...

Then I pushed the code to AppEngine, using ` gcloud app deploy` only (at this time I did not know about `gcloud service-management`, we were not using this before).

When trying to call one of my endpoints then, I got this error 'ApiConfigurationError: POST path "synchro" used multiple times, in classes SQL and Synchro'

That's true, but those two methods are under differents APIs so it should work (it does, in v1).

My code

```
@endpoints.api(name="sql", version='v1.0')
class SQL(remote.Service):
   @endpoints.method(
        CREATE_SYNCHRO,
        message_types.VoidMessage,
        path='synchro',
        http_method='POST',
        name='synchros.start'
    )

@endpoints.api(name='synchro', version='v1.0')
class Synchro(remote.Service):
    @endpoints.method(
        DayUserList,
        UserList,
        path='synchro',
        http_method='POST',
        name='synchronisation'
    )
```
(So migrating from v1 to v2 does not seem to be as simple as Google says... :) )

**Comment by m-murad** [comment]
Facing a similar issue.

**Comment by inklesspen** [comment]
Thanks for the report. I'll look into this soon.

**Comment by inklesspen** [comment]
Not 100% sure this was fixed; reopening to double-check.

**Comment by inklesspen** [comment]
Blocked by #47.

**Comment by inklesspen** [comment]
This has been added to the endpoints [Known Issues](https://cloud.google.com/endpoints/docs/known-issues) page.
