### ISSUE TITLE
Spec generation basePath bug

### ISSUE THREAD

**Issue by sahr** [cloudendpoints/endpoints-python#76]
In v2, if the base path is set to root like so
```python
# resolves to /api/
api_collection = endpoints.api(name='api', version='v1', base_path='/')
```
then this incorrectly produces a spec with the basePath to nothing `""`
```json
{
  "basePath": "/",
  "consumes": [
    "application/json"
  ],
```
when it should leave it as root `"/"`

**Comment by hmiguel** [comment]
@sahr This is kind annoying... For now I changed the line

https://github.com/cloudendpoints/endpoints-python/blob/d2a3ff32dc663a94ebb632f594d23702067b4bfd/endpoints/openapi_generator.py#L976

to 
`'basePath': api_info.base_path.rstrip('/') if api_info.base_path.rstrip('/') != '' else '/',`

cheers
